import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from "react";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-8 h-[100vh] flex flex-col items-center">
          <h1 className="font-bold mb-4">Root Layout</h1>
          <nav className="flex gap-4 p-4 bg-slate-300 text-blue-600 w-[100%]">
            <Link className="underline" href="/">
              Home
            </Link>
            <Link className="underline" href="/person">
              Person
            </Link>
            <Link className="underline" href="/dashboard">
              Dashboard
            </Link>
            <Link className="underline" href="/blog/110">
              Blog
            </Link>
          </nav>
          <div className="flex-1 w-[900px] overflow-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
