import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from "react";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const routerConfig = [
//   {
//     path: "/",
//     name: "Home",
//   },
//   {
//     path: "/person",
//     name: "Person",
//   },
//   {
//     path: "/dashboard",
//     name: "Dashboard",
//   },
//   {
//     path: "/blog/[id]",
//     name: "Blog",
//   },
//   {
//     path: "/intercepting",
//     name: "Intercepting",
//   },
// ];

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-8 h-[100vh] flex flex-col items-center">
          <h1 className="font-bold mb-4">Root Layout</h1>
          <nav className="flex gap-4 p-4 bg-primary text-blue-600 w-[100%] rounded-md">
            <Link className="underline" href="/">
              Home
            </Link>
            <Link className="underline" href="/person">
              Person
            </Link>
            <Link className="underline" href="/dashboard">
              Dashboard
            </Link>
            <Link className="underline" href="/blog/110">
              Blog
            </Link>
            <Link className="underline" href="/intercepting">
              Intercepting
            </Link>
            <Link className="underline" href="/suspense">
              Suspense
            </Link>
            <Link className="underline" href="/todos">
              ToDo
            </Link>
            <Link className="underline" href="/actions-use">
              Actions
            </Link>
          </nav>
          <div className="flex-1 w-[900px] overflow-auto bg-bg-primary">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
